FROM node:20-alpine as base

ARG DATABASE_HOST
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG DATABASE_NAME
ARG DATABASE_PORT
ARG PUBLIC_FRONT_URL

WORKDIR /opt/app

COPY package*.json ./

RUN npm install

RUN npm i -g ts-node-dev

FROM base as dev

ENV PUBLIC_FRONT_URL=$PUBLIC_FRONT_URL
ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_USER=$DATABASE_USER
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_NAME=$DATABASE_NAME
ENV DATABASE_PORT=$DATABASE_PORT

COPY . .

EXPOSE 3001

CMD ["npm", "start"]
